version: '3.8'

services:
  database:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      
  nestjs:
    container_name: core-server
    env_file:
      - ./src/env/.env.development
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database
      - mongodb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg-data: